import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://varofaebpeoqjezzevyk.supabase.co'
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhcm9mYWVicGVvcWplenpldnlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzQxNTMsImV4cCI6MjA3MTExMDE1M30.RKJryxbuhbV66I6WBYaFILGpaNBaVgHV7LWoM9RSquc'
const supabaseServiceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhcm9mYWVicGVvcWplenpldnlrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTUzNDE1MywiZXhwIjoyMDcxMTEwMTUzfQ.QfFRWC_B8uesE_4STJ5eXqxk5pKirmaZ-wFLZtg7d0k'

export const supabase = createClient(supabaseUrl, supabaseAnonKey)
export const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey)
