import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://hfgpiiaphufnjwxwnkjp.supabase.co'
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmZ3BpaWFwaHVmbmp3eHdua2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MjQzMjEsImV4cCI6MjA3MzMwMDMyMX0.pj2kM6wfChR9cIyNgCX5AA9eLU5WQKqwcIb_tETnyms'
const supabaseServiceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmZ3BpaWFwaHVmbmp3eHdua2pwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzcyNDMyMSwiZXhwIjoyMDczMzAwMzIxfQ.jgqJeFKiba1JFYuJvCUWP2Kk6uamBbV6bC6EznPjPsw'

export const supabase = createClient(supabaseUrl, supabaseAnonKey)
export const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey)
